# Generated by Django 3.1.3 on 2020-11-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=75)),
                ('contanct', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('blood_group', models.IntegerField(choices=[(0, '--NA--'), (1, 'A +ve'), (2, 'A -ve'), (3, 'B +ve'), (4, 'B -ve'), (5, 'AB +ve'), (6, 'AB -ve'), (7, 'O +ve'), (8, 'O _ve')], default=0)),
                ('marital_status', models.IntegerField(choices=[(0, 'Married'), (1, 'Unmarried')], default=0)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
