# Generated by Django 3.1.3 on 2020-11-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.IntegerField(choices=[(0, '--NA--'), (1, 'A +ve'), (2, 'A -ve'), (3, 'B +ve'), (4, 'B -ve'), (5, 'AB +ve'), (6, 'AB -ve'), (7, 'O +ve'), (8, 'O -ve')], default=0),
        ),
    ]
