# Generated by Django 3.1.3 on 2020-11-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20201120_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='active',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0),
        ),
    ]
